# Generated by Django 6.0.4 on 2026-06-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_stall_event_alter_stall_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='stall_image',
            field=models.ImageField(blank=True, null=True, upload_to='stall_images/'),
        ),
    ]
