# Generated by Django 6.0.4 on 2026-06-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_stall_stall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
