# Generated by Django 6.0.4 on 2026-06-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_stall_rental_end_date_stall_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
