# Generated by Django 6.0.4 on 2026-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_stall_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='is_active',
            new_name='is_open',
        ),
        migrations.AddField(
            model_name='stall',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
