# Generated by Django 6.0.4 on 2026-06-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_rename_is_active_stall_is_open_stall_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='approval_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='stall',
            name='is_open',
        ),
    ]
