# Generated by Django 6.0.4 on 2026-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_rename_approval_status_stall_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='status',
        ),
        migrations.AddField(
            model_name='stall',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
