# Generated by Django 6.0.4 on 2026-06-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_eventregistration_id'),
        ('events', '0002_event_has_registration_fee_event_registration_fee'),
    ]

    operations = [
    ]
