# Generated by Django 6.0.4 on 2026-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_merge_20260518_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, help_text='Only used for tournament events (number of players per team)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
